name = "AutomaticDocstrings"
uuid = "70b36510-7dee-11e9-28d4-77afe9445f67"
authors = ["Fredrik Bagge Carlson <baggepinnen@gmail.com>"]
version = "1.0.2"

[deps]
CSTParser = "00ebfdb7-1f24-5e51-bd34-a7502290713f"
MacroTools = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09"

[compat]
CSTParser = "2.5"
MacroTools = "0.5.9"
julia = "1.0"

[extras]
DeepDiffs = "ab62b9b5-e342-54a8-a765-a90f495de1a6"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["DeepDiffs", "Test"]
